objects/AwardedQualification__c.object
<CustomObject>
    <fields>
        <fullName>CV__c</fullName>
        <label>CV</label>
        <referenceTo>CurriculumVitae__c</referenceTo>
        <relationshipLabel>Qualifications</relationshipLabel>
        <relationshipName>Awarded_Qualifications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CertificateNumber__c</fullName>
        <label>Certificate Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CertificateURL__c</fullName>
        <label>Certificate URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>FromDate__c</fullName>
        <description>Either date course started or when a certification is valid from</description>
        <inlineHelpText>Either date course started or when a certification is valid from</inlineHelpText>
        <label>From Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Qualification__c</fullName>
        <label>Qualification</label>
        <referenceTo>Qualification__c</referenceTo>
        <relationshipLabel>Qualifications</relationshipLabel>
        <relationshipName>Awarded_Qualifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SortBy__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Sort By</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ToDate__c</fullName>
        <description>Either date course finished or the date, if any, when a certification expires.</description>
        <inlineHelpText>Either date course finished or the date, if any, when a certification expires.</inlineHelpText>
        <label>To Date</label>
        <type>Date</type>
    </fields>
    <label>Awarded Qualification</label>
    <nameField>
        <displayFormat>AQ-{00000}</displayFormat>
        <label>Awarded Qualification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awarded Qualifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CurriculumVitae__c.object
<CustomObject>
    <description>Curriculum Vita or Resume of candidate</description>
    <fields>
        <fullName>Applications__c</fullName>
        <label>Applications</label>
        <picklist>
            <picklistValues>
                <fullName>JIT Resources (Manufacturing ERP System owned by Fourth Shift)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Si-Fi Salesforce App (Business Rules Processing Engine owned by ORIAC Solutions)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TIA (Insurance Application owned by TIA Technology</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CandidateName__c</fullName>
        <formula>Candidate__r.FirstName + &apos; &apos; + Candidate__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Candidate Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Candidate</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Curriculum_Vitae</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MastHeading__c</fullName>
        <label>Mast Heading</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Methodologies__c</fullName>
        <label>Methodologies</label>
        <picklist>
            <picklistValues>
                <fullName>Agile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waterfall</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>SkillSet__c</fullName>
        <globalPicklist>GlobalSkillSetValues</globalPicklist>
        <label>Skill Set</label>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Subtitle__c</fullName>
        <description>Subtitle for CV which would typically be the role/roles of the CV candidate</description>
        <inlineHelpText>Subtitle for CV which would typically be the role/roles of the CV candidate</inlineHelpText>
        <label>Subtitle</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Synopsis__c</fullName>
        <description>Summary or synopsis of the candidate</description>
        <label>Synopsis</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Curriculum Vitae</label>
    <nameField>
        <displayFormat>CV-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Curriculum Vitae</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/CVPosition__c.object
<CustomObject>
    <description>Position forming the Career History of this Candidate&apos;s CV or Resume</description>
    <fields>
        <fullName>CV__c</fullName>
        <description>Link to CV</description>
        <label>CV</label>
        <referenceTo>CurriculumVitae__c</referenceTo>
        <relationshipLabel>Career History</relationshipLabel>
        <relationshipName>CV_Positions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Company that Candidate worked for during this position</description>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Positions</relationshipLabel>
        <relationshipName>CV_Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Job description</description>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>EmploymentType__c</fullName>
        <label>Employment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contract</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Permanent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voluntary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work Experience</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EndMonthYear__c</fullName>
        <formula>CASE( 
DAY( EndDate__c ), 
1, &quot; to Jan&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)), 
2, &quot; to Feb&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)), 
3, &quot; to Mar&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)), 
4, &quot; to Apr&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)), 
5, &quot; to May&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)), 
6, &quot; to Jun&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)), 
7, &quot; to Jul&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)), 
8, &quot; to Aug&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)), 
9, &quot; to Sep&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)), 
10, &quot; to Oct&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)), 
11, &quot; to Nov&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)), 
12, &quot; to Dec&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)), 
&quot; to present&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>End Month Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Any project that this candidate has worked on</description>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>CV_Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsibilities__c</fullName>
        <label>Responsibilities</label>
        <picklist>
            <picklistValues>
                <fullName>Business Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DBA and I&amp;O Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Documentation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estimating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interviewing Potential Developers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liaising with Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mentoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Performance Tuning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Release Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Design and Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TIA Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT Support</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The role that this candidate assumed for this position</description>
        <label>Role</label>
        <referenceTo>Role__c</referenceTo>
        <relationshipLabel>Roles</relationshipLabel>
        <relationshipName>CV_Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SkillsUsed__c</fullName>
        <globalPicklist>GlobalSkillSetValues</globalPicklist>
        <label>Skills Used</label>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date that this position started</description>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartMonthYear__c</fullName>
        <formula>CASE(
  DAY(StartDate__c),
  1, &quot;Jan&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)),
  2, &quot;Feb&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)),
  3, &quot;Mar&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)),
  4, &quot;Apr&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)),
  5, &quot;May&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)),
  6, &quot;Jun&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)),
  7, &quot;Jul&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)),
  8, &quot;Aug&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)),
  9, &quot;Sep&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)),
  10, &quot;Oct&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)),
  11, &quot;Nov&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c)),
  &quot;Dec&quot; + &apos; &apos; + TEXT(YEAR( StartDate__c))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Start Month Year</label>
        <type>Text</type>
    </fields>
    <label>CV Position</label>
    <nameField>
        <displayFormat>CVP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CV Positions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Qualification__c.object
<CustomObject>
    <description>Professional and Academic History</description>
    <fields>
        <fullName>Organisation__c</fullName>
        <label>Organisation</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Qualification</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Qualifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CVController.cls
public with sharing class CVController {
      
    @AuraEnabled
    public static List<String> getSkillsList(){
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = CurriculumVitae__c.SkillSet__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getLabel());
        }

                return options;
    }
       
    @AuraEnabled
    public static List<CurriculumVitae__c> getCVs() {
        system.debug('Start of getCVs...');
        
        /*
        // Check to make sure all fields are accessible to this user
        String[] fieldsToCheck = new String[] {
            'Id', 'Name', 'Amount__c', 'Candidate__c'
        };
        
        Map<String,Schema.SObjectField> fieldDescribeTokens = 
            Schema.SObjectType.CurriculumVitae__c.fields.getMap();
        
        for(String field : fieldsToCheck) {
            if( ! fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
                return null;
            }
        }
        */
        
        // only return if user has access to the fields checked
        return [SELECT id, 
                        name, 
                        CandidateName__c,
                        Candidate__r.name,
                        Candidate__r.title,
                        MastHeading__c,
                        Subtitle__c,
                        Synopsis__c,
                        SkillSet__c,
                        Applications__c,
                        Methodologies__c
                   FROM CurriculumVitae__c];
    } 
        
    @AuraEnabled
    public static CurriculumVitae__c getCV (Id cvId) {
        system.debug('Start of getCV...');
        return [SELECT id, 
                name, 
                CandidateName__c,
                Candidate__r.name,
                Candidate__r.title,
                MastHeading__c,
                Subtitle__c,
                Synopsis__c,
                SkillSet__c,
                Applications__c,
                Methodologies__c
                FROM CurriculumVitae__c
                WHERE Id = :cvId];
    } 
    

    @AuraEnabled
        public static CurriculumVitae__c saveCV(CurriculumVitae__c cv) {
        upsert cv;
        return cv;
        } 
   
    // list to get details of the Curriculum Vita
    public list<CurriculumVitae__c> CVList = new List<CurriculumVitae__c>();
    
    // list to get the Career History from the CV
    public list<CVPosition__c> PositionList = new List<CVPosition__c>();
    
    // list to get the Qualifications linked to this CV
    public list<AwardedQualification__c> QualificationList = new List<AwardedQualification__c>();
    
    // list to get the Academic History linked to this CV
    public list<AwardedQualification__c> AcademicList = new List<AwardedQualification__c>();

    
    // id of the CV we want to display in the Site
    public id cvId = 'a0O24000008Tr3e';
    
    public void StartAction()
       {           
            system.debug('Start of StartAction...');
            PageReference pageRef = apexpages.currentpage();
            pageRef.getParameters().put('Id', cvId);
            //Test.setCurrentPage(pageRef);
            system.debug('currentPage Id: ' + ApexPages.currentPage().getParameters().get('id'));
       }
       
    // getter method for populating CVList and returning values to VF page
    public List<CurriculumVitae__c> getCVList {
       get
       {
           system.debug('Start of getCVList...');
           for (CurriculumVitae__c cv : [select id, 
                                            name, 
                                            Candidate__r.name,
                                            Candidate__r.title,
                                            MastHeading__c,
                                            Subtitle__c,
                                            Synopsis__c,
                                            SkillSet__c,
                                            Applications__c,
                                            Methodologies__c
                                       from CurriculumVitae__c
                                      where id = :ApexPages.currentPage().getParameters().get('id')]) {
                CVList.add(cv);
            }
            system.debug('CVList: ' + CVList);
            return CVList;
       }
       set;
    }
    
    // getter method for populating PositionList and returning values to VF page
    public List<CVPosition__c> getPositionList {
       get
       {
           system.debug('Start of getPositionList...');
           for (CVPosition__c pos : [select id, 
                                            name, 
                                            Description__c, 
                                            Company__r.name, 
                                            Company__r.BillingCity, 
                                            Project__c,
                                            Responsibilities__c, 
                                            Role__c, 
                                            Role__r.name,
                                            SkillsUsed__c,  
                                            StartDate__c, 
                                            StartMonthYear__c, 
                                            EndMonthYear__c, 
                                            CV__c,
                                            EmploymentType__c,
                                            Company__r.CompanyLogo__c
                                       from CVPosition__c
                                      where CV__r.id = :ApexPages.currentPage().getParameters().get('id')
                                      //where CV__r.id = :cvId
                                   order by StartDate__c desc]) {
                PositionList.add(pos);
            }
            system.debug('PositionList: ' + PositionList);
            return PositionList;
       }
       set;
    }
    
    public List<AwardedQualification__c> getQualificationList {
       get
       {
           system.debug('Start of getQualificationList...');
           for (AwardedQualification__c qual : [select id, 
                                                       Qualification__r.name,
                                                       Qualification__r.Organisation__c,
                                                       FromDate__c,
                                                       ToDate__c,  
                                                       CertificateNumber__c,
                                                       CertificateURL__c,
                                                       SortBy__c,
                                                       Qualification__r.Website__c,
                                                       DisplayFromDate__c
                                                  from AwardedQualification__c
                                                 //where CV__r.id = :cvId  
                                                 where CV__r.id = :ApexPages.currentPage().getParameters().get('id') 
                                                   and Certification__c = true                                 
                                                 order by SortBy__c asc]) {
                QualificationList.add(qual);
            }
            system.debug('QualificationList: ' + QualificationList);
            return QualificationList;
       }
       set;
    }
    
       public List<AwardedQualification__c> getAcademicList {
       get
       {
           system.debug('Start of getQualificationList...');
           for (AwardedQualification__c qual2 : [select id, 
                                                       Qualification__r.name,
                                                       Qualification__r.Organisation__c,
                                                       FromDate__c,
                                                       ToDate__c,  
                                                       CertificateNumber__c,
                                                       CertificateURL__c,
                                                       SortBy__c,
                                                       Qualification__r.Website__c,
                                                       DisplayFromDate__c,
                                                       DisplayToDate__c
                                                  from AwardedQualification__c
                                                 //where CV__r.id = :cvId  
                                                 where CV__r.id = :ApexPages.currentPage().getParameters().get('id') 
                                                   and Certification__c = false                                 
                                                 order by SortBy__c asc]) {
                AcademicList.add(qual2);
            }
            system.debug('AcademicList: ' + AcademicList);
            return AcademicList;
       }
       set;
    }

            
   
    public CVController(ApexPages.StandardController controller) {

    }

}